version: "3.1"

services:
  database:
    image: postgres
    container_name: inventory-database

    environment:
      POSTGRES_DB: "inventory"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"

    ports:
      - "5432:5432"

    volumes:
      - "./postgres:/var/lib/postgresql/data"
