version: '3.8'

services:
  app:
    image: laravel:latest
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel-network

  postgres:
    image: postgres:14
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gestdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local